# shell script.

find ../ -iname "*.changes" -maxdepth 1 -print -delete
eval $(ssh-agent)
dch -v "${CI_COMMIT_TAG}.$(lsb_release -s -c)" -D "$(lsb_release -s -c)" -b "Autobuild on Tag ${CI_COMMIT_TAG}"
head debian/changelog
echo "deb http://apt.noris.net $(lsb_release -s -c) main noris" >/etc/apt/sources.list.d/noris.list
apt-get update
dpkg-source -b .
mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes --allow-unauthenticated'   + debian/control

exit 0

cat <<'END'
---

variables:
  CI_GPG_KEYID: "B0F6C87CE7E8AE255509CCB6B9C2AEB2A8AFD611"
  DEBEMAIL: "Gitlab CI <gitlabci-noreply@noris.de>"
  USER: "root"

before_script:
  wget -O - https://gitlab.noris.net/matthias.urlichs/sourcemgr/raw/master/gitlab-ci | /bin/bash
stretch:
  only: 
    - tags
  image: 'docker-registry.noris.net/oci/debbuilder:stretch'
  script:
    - 'dpkg-buildpackage -b -k${CI_GPG_KEYID}'
    - dput -d smurf ../*.changes
buster:
  only:
    - tags
  image: 'docker-registry.noris.net/oci/debbuilder:buster'
  script:
    - 'dpkg-buildpackage -b -k${CI_GPG_KEYID}'
    - dput -d smurf ../*.changes
END
