---

variables:
  CI_GPG_KEYID: "B0F6C87CE7E8AE255509CCB6B9C2AEB2A8AFD611"
  DEBEMAIL: "Gitlab CI <gitlabci-noreply@noris.de>"
  USER: "root"

before_script:
  - "printenv | sort"
  - "apt-get install curl"
  - "curl https://gitlab.noris.net/matthias.urlichs/sourcemgr/raw/master/gitlab-ci | /bin/bash"
stretch:
  only: 
    - tags
  image: 'docker-registry.noris.net/oci/debbuilder:stretch'
  script:
    - 'dpkg-buildpackage -b -k${CI_GPG_KEYID}'
    - dput -d smurf ../*.changes
buster:
  only:
    - tags
  image: 'docker-registry.noris.net/oci/debbuilder:buster'
  script:
    - 'dpkg-buildpackage -b -k${CI_GPG_KEYID}'
    - dput -d smurf ../*.changes
