## autogenerated by 'p.rpm -I STATUS'. Do not edit.

Summary: noris-Paket sourcemgr
Name: sourcemgr
Version: $VERSION$
Release: $RELEASE$

Copyright: 2000, Matthias Urlichs @ noris network GmbH
Group: noris
Source: BK::$ARCHIVE$
Packager: smurf@noris.net
Vendor: noris network GmbH
Prefix: /usr
Requires: rpm-noris
Requires: prcs-noris
Requires: sudo
Requires: shlock

%description
 Zustand unserer Sourcen, Binaries zum Bauen derselben

%prep
%setup -n sourcemgr -T -c
cd ..
rm -rf sourcemgr
if test -d tmp.sourcemgr ; then
    mv -f tmp.sourcemgr sourcemgr
else
    b.get -v noris -d sourcemgr sourcemgr
fi
cd sourcemgr
bk -r get -q

%build
make -f Makefile.Linux compile

%install
make -f Makefile.Linux install

%files
%docdir /usr/info
%docdir /usr/doc
%docdir /usr/man
%docdir /usr/share/info
%docdir /usr/share/doc
%docdir /usr/share/man

%dir /usr/src/STATUS
%dir /usr/src/STATUS/RPM
%dir /usr/src/STATUS/RPM/RPMS
%dir /usr/src/STATUS/RPM/BUILD
%dir /usr/src/STATUS/after
%dir /usr/src/STATUS/checkout
%dir /usr/src/STATUS/cvsup
%dir /usr/src/STATUS/dist
%dir /usr/src/STATUS/done
%dir /usr/src/STATUS/fail
%dir /usr/src/STATUS/hosts
%dir /usr/src/STATUS/keep
%dir /usr/src/STATUS/legacy
%dir /usr/src/STATUS/out
%dir /usr/src/STATUS/packages
%dir /usr/src/STATUS/removed
%dir /usr/src/STATUS/rpm
%dir /usr/src/STATUS/sent
%dir /usr/src/STATUS/skip
%dir /usr/src/STATUS/status
%dir /usr/src/STATUS/subst
%dir /usr/src/STATUS/to-install
%dir /usr/src/STATUS/work
/usr/src/STATUS/rpmmacros
/usr/src/STATUS/rpmrc
/usr/src/STATUS/checkout/*
/usr/local/bin/p.h
/usr/local/bin/put
/usr/local/bin/p.bk
/usr/local/bin/redo
/usr/local/bin/build
/usr/local/bin/p.add
/usr/local/bin/p.del
/usr/local/bin/p.get
/usr/local/bin/p.new
/usr/local/bin/p.put
/usr/local/bin/p.rpm
/usr/local/bin/retag
/usr/local/bin/vicon
/usr/local/bin/cpdisk
/usr/local/bin/mkdisk
/usr/local/bin/p.diff
/usr/local/bin/p.edit
/usr/local/bin/p.info
/usr/local/bin/p.init
/usr/local/bin/p.make
/usr/local/bin/p.name
/usr/local/bin/p.oget
/usr/local/bin/dopatch
/usr/local/bin/p.bk.pl
/usr/local/bin/p.merge
/usr/local/bin/p.patch
/usr/local/bin/p.rdist
/usr/local/bin/p.rekey
/usr/local/bin/p.rmcvs
/usr/local/bin/fixafter
/usr/local/bin/p.bktest
/usr/local/bin/p.export
/usr/local/bin/p.import
/usr/local/bin/stripall
/usr/local/bin/build.alt
/usr/local/bin/gen.flist
/usr/local/bin/gen.rdist
/usr/local/bin/p.rcvsget
/usr/local/bin/p.scvsget
/usr/local/bin/p.version
/usr/local/bin/p.rrcvsget
/usr/local/bin/p.cvsimport
/usr/local/bin/p.unchecked
/usr/local/bin/gen.distfile
/usr/local/bin/gen.flist.rpm
