#!/bin/sh
set -e

git config --system alias.ls >/dev/null || \
git config --system --add alias.ls "ls-files"

git config --system alias.lso >/dev/null || \
git config --system --add alias.lso "ls-files --others --exclude-standard"

#DEBHELPER#
